---
apiVersion: v2
type: application
appVersion: "0.32.0"
version: 3.0.1
name: vouch
description: An SSO and OAuth login solution for nginx using the auth_request module
icon: https://avatars0.githubusercontent.com/u/45102943?s=200&v=4
keywords:
  - nginx
  - auth
  - oauth2
  - authentication
  - nginx-proxy
  - sso
  - sso-login
home: https://github.com/vouch/vouch-proxy/
sources:
  - https://github.com/vouch/vouch-proxy/
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Fix ingress templates for k8s older than 1.19
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: vouch-proxy
      image: quay.io/vouch/vouch-proxy:0.32.0
