{{- if not .Values.existingSecretName }}
{{- $vouchSecret := required "`config.vouch.jwt.secret` is not set and we are no longer providing a weak default" .Values.config.vouch.jwt.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vouch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vouch.name" . }}
    helm.sh/chart: {{ include "vouch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  config.yaml: |
{{- if .Values.config.vouch }}
    vouch:
{{ toYaml .Values.config.vouch | indent 6 }}
{{- end }}
{{- if .Values.config.oauth }}
    oauth:
{{ toYaml .Values.config.oauth | indent 6 }}
{{- end }}
{{- end }}
